export { LoginPage } from './login/index.js';
export { RegistrationPage } from './registration';
export { ProfilePage } from './profile/index.js';
export { EditProfilePage } from './edit-profile/index.js';
export { ChangePasswordPage } from './change-password/index.js';
export { ChatListPage } from './chat-list/index.js';
export { ChatPage } from './chat/index.js';
export { NotFoundErrorPage } from './404/index.js';
export { ServerErrorPage } from './500/index.js';
